// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API key validation request/response
 */
export type ApiKeyValidationRequest = { provider: string, api_key: string, };
