// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channel token validation response
 */
export type ChannelValidationResponse = { valid: boolean, error: string | null, bot_name: string | null, bot_username: string | null, };
