// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channel token validation request
 */
export type ChannelValidationRequest = { platform: string, token: string, app_token: string | null, };
