// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channel configuration for saving
 */
export type ChannelConfig = { platform: string, enabled: boolean, bot_token: string | null, app_token: string | null, dm_policy: string, allowed_users: Array<string>, };
