// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ChannelHealth - individual channel status
 */
export type ChannelHealth = { platform: string, status: string, last_active: string | null, error_message: string | null, };
