// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Command execution output
 */
export type CommandOutput = { stdout: string, stderr: string, exit_code: number, };
