// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a Docker container
 */
export type ContainerStatus = "Running" | "Stopped" | "Created" | "Exited" | "Error";
