// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerStatus } from "./ContainerStatus";

/**
 * Information about a managed Docker container
 */
export type ContainerInfo = { id: string, name: string, image: string, status: ContainerStatus, created_at: string, port: number | null, };
