// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Container log output
 */
export type ContainerLogsResponse = { container_id: string, logs: Array<string>, };
