// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AI-powered cost optimization recommendation
 */
export type CostRecommendation = { current_model: string, recommended_model: string, current_cost_monthly: number, recommended_cost_monthly: number, savings_monthly: number, savings_percent: number, use_case: string, rationale: string, };
