// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostRecommendation } from "./CostRecommendation";

/**
 * Full cost analysis result with recommendations
 */
export type CostAnalysis = { recommendations: Array<CostRecommendation>, total_current_monthly: number, total_recommended_monthly: number, total_savings_monthly: number, analysis_date: string, summary: string | null, };
