// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DaemonStatus - returned by daemon status endpoint
 */
export type DaemonStatus = { running: boolean, pid: number | null, uptime_seconds: bigint | null, memory_mb: bigint | null, cpu_percent: number | null, };
