// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DaemonActionResponse - returned by start/stop/restart
 */
export type DaemonActionResponse = { success: boolean, message: string, };
