// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual diagnostic check from openclaw doctor
 */
export type DiagnosticCheck = { name: string, 
/**
 * "pass", "fail", or "warn"
 */
status: string, message: string, fix_suggestion: string | null, };
