// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerInfo } from "./ContainerInfo";

/**
 * Docker daemon status and running containers
 */
export type DockerStatusResponse = { available: boolean, version: string | null, containers: Array<ContainerInfo>, error: string | null, };
