// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response after creating a Docker container
 */
export type DockerCreateResponse = { success: boolean, container_id: string | null, port: number | null, error: string | null, };
