// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new Docker sandbox container
 */
export type DockerCreateRequest = { name: string, 
/**
 * Docker image to use; defaults to "node:20-alpine" if None
 */
image: string | null, };
