// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticCheck } from "./DiagnosticCheck";

/**
 * Full diagnostic report from openclaw doctor
 */
export type DoctorReport = { checks: Array<DiagnosticCheck>, 
/**
 * "healthy", "warning", or "critical"
 */
overall_status: string, timestamp: string, };
