// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Concrete API response with no data for TypeScript export
 */
export type EmptyResponse = { success: boolean, error: string | null, };
