// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelHealth } from "./ChannelHealth";

/**
 * HealthSnapshot - returned by health endpoint
 */
export type HealthSnapshot = { gateway_reachable: boolean, gateway_mode: string, channels: Array<ChannelHealth>, session_count: number, probe_duration_ms: number, };
