// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Installation progress update
 */
export type InstallProgress = { stage: string, status: string, message: string, output_line: string | null, error: string | null, progress_pct: number | null, };
