// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a locally installed skill
 */
export type InstalledSkill = { name: string, version: string, path: string, size_bytes: bigint | null, };
