// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LLM model pricing information
 */
export type LlmModelPricing = { provider: string, model: string, input_per_million: number, output_per_million: number, context_window: number | null, notes: string | null, };
