// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmModelPricing } from "./LlmModelPricing";

/**
 * LLM pricing response with all available models
 */
export type LlmPricingResponse = { models: Array<LlmModelPricing>, last_updated: string, };
