// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * AI-generated analysis of log errors
 */
export type LogAnalysis = { error_summary: string, cause: string, fix_steps: Array<string>, confidence: string, };
