// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single log line with optional parsed metadata
 */
export type LogLine = { content: string, timestamp: string | null, level: string | null, };
