// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLine } from "./LogLine";

/**
 * Response containing recent log lines
 */
export type LogsResponse = { service: string, lines: Array<LogLine>, total: number, };
