// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to deploy to multiple servers
 */
export type MultiServerDeployRequest = { server_ids: Array<string>, };
