// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress update for a single server during multi-server deployment
 */
export type MultiServerProgress = { server_id: string, server_name: string, stage: string, status: string, message: string, error: string | null, timestamp: bigint, };
