// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OpenClaw detection result
 */
export type OpenClawDetection = { installed: boolean, version: string | null, install_path: string | null, config_found: boolean, config_path: string | null, existing_config: Record<string, any> | null, };
