// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remote installation request (sent via WebSocket)
 */
export type RemoteInstallRequest = { host: string, username: string, 
/**
 * Optional: override WizardConfig from saved config
 */
config: Record<string, any> | null, };
