// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remote setup progress update (streamed via WebSocket)
 */
export type RemoteSetupProgress = { 
/**
 * Current installation stage
 */
stage: string, 
/**
 * Stage status
 */
status: string, 
/**
 * User-visible message
 */
message: string, 
/**
 * Error details if status is failed
 */
error: string | null, 
/**
 * Unix timestamp (seconds)
 */
timestamp: bigint, };
