// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual requirement check result
 */
export type RequirementCheck = { name: string, required: string, actual: string, passed: boolean, help_text: string | null, };
