// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RollbackStage } from "./RollbackStage";

/**
 * Result of a rollback operation
 */
export type RollbackResult = { success: boolean, stages: Array<RollbackStage>, error: string | null, };
