// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single stage in the rollback process
 */
export type RollbackStage = { name: string, 
/**
 * "pending", "success", "skipped", "failed"
 */
status: string, message: string, };
