// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to scan a skill package
 */
export type ScanRequest = { skill_name: string, version: string, };
