// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreatLevel } from "./ThreatLevel";

/**
 * Result of a VirusTotal security scan
 */
export type ScanResult = { threat_level: ThreatLevel, malicious_count: number, suspicious_count: number, total_scanners: number, scan_date: string, permalink: string | null, };
