// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual security finding from audit
 */
export type SecurityFinding = { id: string, 
/**
 * "critical", "warning", or "info"
 */
severity: string, title: string, description: string, affected_field: string, fix_suggestion: string | null, };
