// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecurityFinding } from "./SecurityFinding";

/**
 * Full security audit result
 */
export type SecurityAudit = { findings: Array<SecurityFinding>, 
/**
 * "secure", "warnings", or "critical"
 */
overall_score: string, critical_count: number, warning_count: number, audit_date: string, };
