// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response after performing a service action (start/stop/restart)
 */
export type ServiceActionResponse = { success: boolean, service: string, message: string, };
