// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of testing a server connection
 */
export type ServerTestResult = { server_id: string, success: boolean, message: string, };
