// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A target server for multi-server deployment
 */
export type ServerTarget = { id: string, name: string, host: string, username: string, key_path: string, 
/**
 * "pending", "connected", "failed", "deployed"
 */
status: string, };
