// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceProcessStatus } from "./ServiceProcessStatus";

/**
 * Combined status of all OpenClaw services with system metrics
 */
export type ServicesStatus = { gateway: ServiceProcessStatus, daemon: ServiceProcessStatus, error_count_24h: number, system_cpu_percent: number | null, system_memory_total_mb: bigint | null, system_memory_used_mb: bigint | null, };
