// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of deploying to a single server
 */
export type ServerDeployResult = { server_id: string, server_name: string, success: boolean, error: string | null, completed_stages: Array<string>, };
