// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of an individual service process (gateway or daemon)
 */
export type ServiceProcessStatus = { running: boolean, pid: number | null, uptime_seconds: bigint | null, memory_mb: bigint | null, cpu_percent: number | null, };
