// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillCategory } from "./SkillCategory";

/**
 * Request to search for skills
 */
export type SkillSearchRequest = { query: string | null, category: SkillCategory | null, };
