// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillMetadata } from "./SkillMetadata";

/**
 * Response from a skill search
 */
export type SkillSearchResponse = { skills: Array<SkillMetadata>, total: number, };
