// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanResult } from "./ScanResult";

/**
 * Response after installing a skill
 */
export type SkillInstallResponse = { success: boolean, name: string, version: string, error: string | null, scan_result: ScanResult | null, };
