// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillCategory } from "./SkillCategory";

/**
 * Metadata about a skill from the ClawHub registry
 */
export type SkillMetadata = { name: string, version: string, description: string, author: string, category: SkillCategory, tags: Array<string>, capabilities: Array<string>, homepage: string | null, repository: string | null, downloads: number | null, verified: boolean, };
