// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to install a skill
 */
export type SkillInstallRequest = { name: string, 
/**
 * Version to install; None = latest
 */
version: string | null, };
