// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category classification for skills
 */
export type SkillCategory = "DevTools" | "DataProcessing" | "ApiIntegration" | "Automation" | "Security" | "Monitoring" | "Other";
