// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSH connection request for testing or establishing connection
 */
export type SshConnectionRequest = { host: string, username: string, key_path: string, };
