// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SSH connection status and details
 *
 * Validation rules:
 * - host: Must match `^[a-zA-Z0-9.-]+$` (hostname or IP)
 * - username: Must match `^[a-z_][a-z0-9_-]*$` (valid Unix username)
 * - key_path: Absolute path or `~/.ssh/id_*` pattern
 */
export type SshConnection = { host: string, username: string, key_path: string, connected: boolean, error: string | null, };
