// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshConnection } from "./SshConnection";

/**
 * SSH connection test response
 */
export type SshConnectionResponse = { success: boolean, message: string, connection: SshConnection | null, };
