// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequirementCheck } from "./RequirementCheck";

/**
 * Full system requirements response
 */
export type SystemRequirements = { checks: Array<RequirementCheck>, all_passed: boolean, node_installed: boolean, node_version: string | null, };
