// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System information structure
 */
export type SystemInfo = { os: string, arch: string, node_version: string | null, openclaw_installed: boolean, };
