// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemInfo } from "./SystemInfo";

/**
 * Concrete API response with SystemInfo for TypeScript export
 */
export type SystemInfoResponse = { success: boolean, data: SystemInfo | null, error: string | null, };
