// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Threat level determined by VirusTotal scan
 */
export type ThreatLevel = "Clean" | "Suspicious" | "Malicious";
