// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelConfig } from "./ChannelConfig";

/**
 * Wizard config to save
 */
export type WizardConfig = { provider: string, api_key: string, 
/**
 * "api-key", "setup-token", "oauth", or "skip"
 */
auth_type: string, gateway_port: number, gateway_bind: string, auth_mode: string, auth_credential: string | null, channels: Array<ChannelConfig> | null, base_url: string | null, model_id: string | null, 
/**
 * "openai" or "anthropic" (Custom provider compatibility mode)
 */
compatibility: string | null, 
/**
 * Cloudflare account ID
 */
account_id: string | null, 
/**
 * Cloudflare gateway ID
 */
gateway_id: string | null, };
